name: CI

on:
  push:
    paths:
      - 'cloud-run/api-gw/backend/**'
      - '.github/workflows/example_backend.yml'

env: 
  PROJECT_ID: main-104
  SERVICE_NAME: simpleserver

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build the Docker Image 
      run: docker build simpleserver -t gcr.io/main-104/$SERVICE_NAME
    
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: ‘274.0.0’
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
    
    - run: gcloud auth configure-docker

    - name: Push image
      run: docker push gcr.io/$PROJECT_ID/$SERVICE_NAME
    
    - name: Cloud Run Deploy 
      run: |
          gcloud run deploy $SERVICE_NAME \
            --project $PROJECT_ID \
            --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
            --platform managed \
            --region us-central1 
      
